// Package envvar handles creation and merging of environment variable files.
package envvar

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Writer creates and updates .env files.
type Writer struct {
	projectDir string
}

// NewWriter creates a new env var writer.
func NewWriter(projectDir string) *Writer {
	return &Writer{projectDir: projectDir}
}

// Write writes environment variables to a .env file in the project directory.
// Existing values are preserved (not overwritten) unless explicitly set in the config.
func (w *Writer) Write(vars map[string]string) error {
	envPath := filepath.Join(w.projectDir, ".env")

	// Load existing .env if present
	existing, err := w.loadExisting(envPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("reading existing .env: %w", err)
	}

	// Merge: config values are written only if the key doesn't already exist
	merged := make(map[string]string)
	for k, v := range vars {
		merged[k] = v
	}
	for k, v := range existing {
		merged[k] = v // existing values take precedence
	}

	// Write back
	return w.writeFile(envPath, merged)
}

// MergeFromFile reads KEY=VALUE pairs from a template file and merges them.
func (w *Writer) MergeFromFile(templatePath string, target map[string]string) error {
	absPath := filepath.Join(w.projectDir, templatePath)
	parsed, err := w.loadExisting(absPath)
	if err != nil {
		return fmt.Errorf("reading template file %s: %w", templatePath, err)
	}

	for k, v := range parsed {
		if _, exists := target[k]; !exists {
			target[k] = v
		}
	}

	return nil
}

// loadExisting reads a .env file into a map.
func (w *Writer) loadExisting(path string) (map[string]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	vars := make(map[string]string)
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		// Skip comments and empty lines
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			value := strings.TrimSpace(parts[1])
			// Remove surrounding quotes
			value = strings.Trim(value, `"'`)
			vars[key] = value
		}
	}

	return vars, scanner.Err()
}

// writeFile writes env vars to a file in sorted order.
func (w *Writer) writeFile(path string, vars map[string]string) error {
	// Sort keys for deterministic output
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var lines []string
	lines = append(lines, "# Generated by OneConfig — do not edit manually")
	lines = append(lines, "# To customize, update your oneconfig.yml and run 'oneconfig up'")
	lines = append(lines, "")

	for _, k := range keys {
		v := vars[k]
		// Quote values that contain spaces or special characters
		if strings.ContainsAny(v, " \t#=") {
			v = fmt.Sprintf(`"%s"`, v)
		}
		lines = append(lines, fmt.Sprintf("%s=%s", k, v))
	}
	lines = append(lines, "")

	return os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0600)
}
